### ISSUE TITLE
登录成功后过了30s 自动推出，如此反复什么情况？

### ISSUE THREAD

**Issue by DancingLeaf123** [vikiboss/genshin-helper#11]
![image](https://user-images.githubusercontent.com/23498471/201060208-5dd6cf3b-c0ed-48e5-8543-87f87aeeec94.png)
![image](https://user-images.githubusercontent.com/23498471/201060355-274e40cd-0def-4754-b2ff-bdd6e5f51b32.png)

**Comment by vikiboss** [comment]
自动退出的时候有什么提示吗？比如验证信息已过期？🤔

**Comment by DancingLeaf123** [comment]
是的，就是提示那个信息已过期或者未绑定uid，不过显然既然已经登录成功了，是绑定了uid的才对。

**Comment by lostsnow** [comment]
![图片](https://user-images.githubusercontent.com/220461/201108289-f8a6fef9-261e-4370-a6a4-1d24d31d3ae1.png)
![图片](https://user-images.githubusercontent.com/220461/201108324-10d89b5e-8578-4dc7-a811-e51b6462b748.png)
![图片](https://user-images.githubusercontent.com/220461/201108376-fc84ec95-f5d5-4016-8c90-6ac5d76a2d54.png)

**Comment by DancingLeaf123** [comment]
我晚上又试了试，似乎不退出了，不清楚原因。
不过我去米游社签到了，过了5分钟，刷新了数据还是提示没签到

**Comment by vikiboss** [comment]
你们的原因应该都是与最近米游社新加的验证码有关系（不仅是签到，还有个人战绩页等），如果发现数据获取失败，请到米游社APP的个人战绩页面看看是不是账号安全风险，需要手动过验证码。过完验证码就可以了，这个问题目前暂时无解，等后面再看看。

**Comment by lostsnow** [comment]
> 你们问题的原因应该都是与最近米游社新加的验证码有关系（不仅是签到，还有个人战绩页等），如果发现数据获取失败，请到米游社APP的个人战绩页面看看是不是账号安全风险，有时候需要手动过验证码。过完验证码再次尝试看看。这个问题目前暂时无解，等后面再看看。

试了下确实是这个问题
