### ISSUE TITLE
无法登录米游社，显示404

### ISSUE THREAD

**Issue by winter12138** [vikiboss/genshin-helper#13]
![image](https://user-images.githubusercontent.com/22698289/201907996-1dd234b6-f7c8-4bfd-aa64-9401c4f82d77.png)

**Comment by vikiboss** [comment]
应该是米游社近期修改了登录页面链接。
可以点击这个页面左上角的返回，手动找到登录框进行登录，成功之后关闭即可

**Comment by vikiboss** [comment]
请更新到 1.1.5
