### ISSUE TITLE
可以添加一个针对角色的圣遗物评分吗？我看有些qq群聊机器人有这个功能

### ISSUE THREAD

**Issue by DancingLeaf123** [vikiboss/genshin-helper#14]

**Comment by vikiboss** [comment]
首先非常感谢你的使用和支持。

圣遗物评分这个功能其实一直有在考虑，但是想用心做好这个功能，需要考虑的东西还是挺多的。

1. 目前很多圣遗物评分工具的**评分规则不一**，评分算法要想设计得科学好用，需要**考虑很多因素**。不同配队、不同角色、不同流派打法，以及你升级圣遗物歪了没歪，歪了几次，歪的影响对评分结果影响如何度量，还有不同的词条基值的优劣差异的规则等，情况太多，且没有一个约定的评分规则来统一。

2. 再一个就是**不太好处理用户交互**。我也之前有调查过一些在线工具，有使用上传截图识别的，也有手动输入的。上传截图识别有点困难，手动让用户输又影响体验，目前还没有很好的一个交互的方式，所以没写。

3. 最后就是，这部分的**工作量确实比较大**，我目前也有很多其他的事情和自己的项目要处理，没有很多精力来维护这个项目。

**Comment by DancingLeaf123** [comment]
好的，感谢你详细地回复。目前我估计大部分都只是用了一般化的算法，比如忽略配对，歪与否这些。最多考虑一下角色。我也感觉一个完善的评分系统估计是挺大工作量的，数据收集也不容易。
