### ISSUE TITLE
已经24天没有更新了，打卡和更新数据遇到验证码都歇菜。

### ISSUE THREAD

**Issue by clm0081** [vikiboss/genshin-helper#16]
生产队的驴都歇够了，希望viki可以尽快出新版本解决上述问题，不要不识好歹。

**Comment by vikiboss** [comment]
~~嘤嘤嘤~~，当前没有空闲时间处理这个项目，有其他事情要忙 QAQ。

> https://github.com/KiviBotLab/KiviBot

**Comment by vikiboss** [comment]
1.1.5 做了一部分优化
