### ISSUE TITLE
【祈愿分析】该如何获取链接？

### ISSUE THREAD

**Issue by Hydsiun** [vikiboss/genshin-helper#17]
第一次用这种分析软件，可否在readme里面提一下呀大佬~

**Comment by vikiboss** [comment]
~~原来是第一次用这种软件吗（~~

好嘞，最近在重构屎代码，在 Windows 下，你可以通过：

1. 本地电脑打开原神游戏，打开祈愿页面，点击历史记录，往后翻几页。
2. 重新打开软件的祈愿分析页，顺利的话，会自动填充祈愿链接。
3. 如果没有自动填充，按照以下步骤进行操作：

- `Windows 徽标键` + `R` 打开运行窗口，输入 cmd 回车。
- 在弹出的黑框里，输入以下代码并回车，顺利的话，会自动获取并复制到剪切板。

```shell
iex "&{$(irm https://gist.githubusercontent.com/MadeBaruna/1d75c1d37d19eca71591ec8a31178235/raw/702e34117b07294e6959928963b76cfdafdd94f3/getlink.ps1)} china"
```

> 注意：以上方法仅适用于本地 Windows 电脑上安装了原神游戏本体。

**Comment by Hydsiun** [comment]
哈哈，原来是这样。非常感谢~
是的，因为我之前一直在平板上玩，然后就突发奇想想找一下有没有桌面版的原神助手，然后就找到了你们这款，用着还是很舒心的~
如果能出些桌面插件就更好啦哈哈

**Comment by vikiboss** [comment]
关于祈愿链接的相关说明已添加到 [readme](https://github.com/vikiboss/genshin-helper#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E7%A5%88%E6%84%BF%E9%93%BE%E6%8E%A5)。

桌面插件不太好搞，需单独处理好多东西，而且效果不一定好，暂时不考虑。
