### ISSUE TITLE
图标显示不全

### ISSUE THREAD

**Issue by xiaotian2333** [vikiboss/genshin-helper#2]
系统：系统win10x64 21h2(19044.1645)
原神助手版本：1.1.0
如同所示

![image](https://user-images.githubusercontent.com/79242764/181266152-c32f4f97-c673-4a48-b529-3064bea9cfdd.png)

![image](https://user-images.githubusercontent.com/79242764/181266182-40d01aa5-d0cc-4983-8cdb-542fc3f106f4.png)

**Comment by MikeyShell** [comment]
同样存在这个问题

**Comment by vikiboss** [comment]
之前的 icon 图标太大，导致显示不全，已压缩优化 ico 图标文件的大小。
