### ISSUE TITLE
1.1.5版本材料日历中点击武器材料会发生跳转

### ISSUE THREAD

**Issue by MikeyShell** [vikiboss/genshin-helper#20]
1.1.5版本材料日历选择按武器查看，点击相应武器图片后会发生跳转，跳转回默认的按角色查看页面，这个特性跟之前版本不一样，对于想查看多个武器材料情况不是很方便，不知道这个是属于bug还是feature。

平台：Windows 10 X64

**Comment by vikiboss** [comment]
草，应该是重构的时候写 BUG 了，感谢反馈，晚点修一下，然后可以到 Action 页面下载最新构建版本

**Comment by MikeyShell** [comment]
哈哈，好的谢谢，感谢大佬更新维护工具

**Comment by MikeyShell** [comment]
还有一个问题顺便反馈给大佬，最新活动的鬼伞东花坊时雨在材料日历里面也没有看到，不知道这个是需要手动维护还是获取米游社的数据，在米游社中看能查到这把伞。

**Comment by vikiboss** [comment]
材料数据以及生日信息来源于[米游社观测枢的材料日历](https://bbs.mihoyo.com/ys/obc/channel/map/193?bbs_presentation_style=no_header)，你可以切换到周日（显示所有材料），然后发现他其实到目前(2023/1/3 15:43)为止并没有这个武器，它好像还没有更新，等待他更新吧。

**Comment by vikiboss** [comment]
材料页异常跳转已修复，你可以到 [Actions 页](https://github.com/vikiboss/genshin-helper/actions/runs/3827697223)往下滑，找到 `GenshinHelper_windows-lates`，下载最新构建版本。

**Comment by MikeyShell** [comment]
> 材料数据以及生日信息来源于[米游社观测枢的材料日历](https://bbs.mihoyo.com/ys/obc/channel/map/193?bbs_presentation_style=no_header)，你可以切换到周日（显示所有材料），然后会发现，其实到目前(2023/1/3 15:43)为止并没有这个武器，好像还没有更新，等待他更新吧。

好的
