### ISSUE TITLE
多个建议合并

### ISSUE THREAD

**Issue by xiaotian2333** [vikiboss/genshin-helper#3]
## 抽卡模拟功能
模拟游戏内抽卡，可自定义卡池，概率等

## 游戏角色生日提醒
角色生日当天主页提醒或出现单独页面
> 可能需要考虑同一天多个角色生日的问题

如果能对接到米游社的生日祝福页面就更好了

## 圣遗物评分
可参考[可莉特调](https://genshin.pub/relic)的圣遗物评分（或直接对接）

## 扫码登陆游戏功能
类似米游社手机端的扫码登陆游戏功能，通过捕捉屏幕截图识别二维码实现免密码登陆

米游社的入口如图
![扫码入口](https://user-images.githubusercontent.com/79242764/181270777-37755248-db4f-463d-bf8d-95de028d02d6.png)
这个是扫码过程的截图
![界面截图](https://user-images.githubusercontent.com/79242764/181270929-a68c5293-16fe-4e30-b108-d0f83140e98f.jpg)

**Comment by vikiboss** [comment]
都是不错的建议，下面对这些建议发表我自己的看法：

- **抽卡模拟功能**，已在“传送门”页添加老外写的一个抽卡模拟链接，自己写太麻烦了，想写好很费精力
- **游戏角色生日提醒**，这个在 1.1.4 版本已添加，当天有角色生日时首页的 tip 文字会有提醒，对接米游社的页面比较麻烦，他可能需要调用一些米游社APP内部的 api 和数据，这个我是拿不到的
- **圣遗物评分**，参考 #14，另外，~~[可莉特调](https://genshin.pub/relic)的网站好像挂了~~
- **扫码登录游戏**，同 2，可能需要调用一些米游社APP内部的 api 和数据，这个我是拿不到的
