### ISSUE TITLE
账号切换

### ISSUE THREAD

**Issue by poify** [Vikiboss/genshin-helper#5]
其他可以，账号切换可以快捷吗，直接主界面切换

**Comment by Vikiboss** [comment]
1. 主界面空间有限。
2. 从功能考虑，这个切换直接放主页很奇怪。
3. 这不属于通用需求，可能只是你自己切换的很频繁。
4. 目前只多了一层交互，到切换页就能切换，也不是很复杂。

综上，暂不考虑在主页直接舔加切换账号的功能。
