### ISSUE TITLE
关于祈愿的建议

### ISSUE THREAD

**Issue by TremblingMoeNew** [Vikiboss/genshin-helper#7]
1. 既然储存格式和导出格式都是通用祈愿格式（JSON），那完全可以用同一套逻辑。现在两边的`info`都不一致，储存那边的`export_app`是中文的而且没版本号。
2. 获取记录建议加上代理模式和从Web缓存获取~~可以抄下其他工具~~。

~~[关注祈愿记录格式库喵](https://dodocotales.cc/#/wish-log-formats/)，[关注祈愿记录格式库谢谢喵](https://github.com/TremblingMoeNew/DodocoTales-docs)~~

**Comment by Vikiboss** [comment]
好的，感谢你的建议，下个版本更新时将对储存格式和导出格式进行统一，同时将视情况看是否引入代理获取链接的方式（目前在考虑直接通过米哈游通行证的方式，免链接获取游戏数据、祈愿数据等）。

> 我一开始以为“储存格式”用户应该接触的少，仅作软件内部标识和缓存使用，但目前看来确实不排除部分用户直接使用储存格式数据进行软件间互通的可能。
