### ISSUE TITLE
能否加个Mac版啊

### ISSUE THREAD

**Issue by zhangferry** [vikiboss/genshin-helper#9]
不知道对Win系统依赖多不多，如果完全是Electron和React的话，迁移成本应该还可以吧

**Comment by Vikiboss** [comment]
其实已经支持了，配置好了多平台的打包选项, "关于"页面也写了支持多平台。 ~~只是我没有 Mac 调试不了也打包不了 2333~~
你可以自己把仓库拉下来，尝试在 `mac` 下使用 `npm i` 安装依赖，然后使用 `npm run package` 构建一下
> 但可能会有一些系统兼容问题，比如托盘菜单 icon 的表现

**Comment by Vikiboss** [comment]
应该没有依赖于特定的平台依赖，主要差异在于缓存的存储路径，以及 `Electron` 做了打平的一些 `native api` 的表现可能会有所差异

**Comment by zhangferry** [comment]
@Vikiboss 楼主你好，我尝试在macbook上用npm打包时遇到下面的异常，没太看明白为啥，能帮看下不：
![image](https://user-images.githubusercontent.com/13702445/194765047-705d247f-f1d8-47c1-9a89-f8277635e3ce.png)

**Comment by Vikiboss** [comment]
应该是不同系统平台的文件命名大小写敏感性问题，参考 `TypeScript` 的这个 [issue](https://github.com/microsoft/TypeScript/issues/25460#issuecomment-479949649)

但我在开发的时候都是用的 Windows 没有发现异常，以至于我无法察觉到这个 `bug`。

晚点我统一一下文件引入的大小写，你尝试 `git pull` 之后再 `npm run package` 构建一下试试。

~~PS: issue 是你开的，理论上你才是楼主~~

**Comment by Vikiboss** [comment]
尝试使用以下方式拉取最新代码，删除模块缓存和构建缓存后重新构建：

1. 切换到项目目录执行 `git pull` 确保同步最新代码
2. 删除项目目录下的 `.webpack` 缓存目录，如果有的话
3. 删除项目目录下的 `node_modules` 依赖目录，重新 `npm install` 安装依赖
4. 执行 `npm run package` 尝试构建
5. 如果构建成功，构建结果在项目目录的 `out` 目录下

**Comment by zhangferry** [comment]
> 应该是不同系统平台的文件命名大小写敏感性问题，参考 `TypeScript` 的这个 [issue](https://github.com/microsoft/TypeScript/issues/25460#issuecomment-479949649)
> 
> 但我在开发的时候都是用的 Windows 没有发现异常，以至于我无法察觉到这个 `bug`。
> 
> 晚点我统一一下文件引入的大小写，你尝试 `git pull` 之后再 `npm run package` 构建一下试试。
> 
> ~PS: issue 是你开的，理论上你才是楼主~

~好的，楼主，主要不知道该怎么称呼了。。~ 我看最新的commit是3天前的，应该还没更新吧。已经确保了代码最新和缓存重置，还是会有那个问题。列出的issues里有一个方案是在tsconfig.json里加"forceConsistentCasingInFileNames": false 试了也不行。我对了一下报错路径，确实会有大小写的问题，得等你更新之后才能测试吧

**Comment by Vikiboss** [comment]
> > 应该是不同系统平台的文件命名大小写敏感性问题，参考 `TypeScript` 的这个 [issue](https://github.com/microsoft/TypeScript/issues/25460#issuecomment-479949649)
> > 但我在开发的时候都是用的 Windows 没有发现异常，以至于我无法察觉到这个 `bug`。
> > 晚点我统一一下文件引入的大小写，你尝试 `git pull` 之后再 `npm run package` 构建一下试试。
> > ~PS: issue 是你开的，理论上你才是楼主~
> 
> ~好的，楼主，主要不知道该怎么称呼了。。~ 我看最新的commit是3天前的，应该还没更新吧。已经确保了代码最新和缓存重置，还是会有那个问题。列出的issues里有一个方案是在tsconfig.json里加"forceConsistentCasingInFileNames": false 试了也不行。我对了一下报错路径，确实会有大小写的问题，得等你更新之后才能测试吧

再试试呢，这阵子挺忙的没太注意。

**Comment by zhangferry** [comment]
文件管理好像还是有问题，我在github看src/render/pages目录内容大写小写各一份，拉下来还是大写的内容。我手动改了文件夹名称可以完成编译了

**Comment by vikiboss** [comment]
本地改完大小写被他直接合并了，远程没有删除已经改名的部分。
